[package]
name = "rustaclysm"
version = "0.1.0"
authors = ["papow65 <papow65@protonmail.com>"]
edition = "2021"

[dependencies]
bevy = { version = "0.8.*", features = [ "dynamic", "trace", "wayland" ] }
pathfinding = "2.*"
bresenham = "0.1.*"
rand = "0.8.*"
serde = { version = "1.*", features = [ "derive" ] }
serde_json = "1.*"
glob = "0.3.*"
chrono = "0.4.*"

[profile.dev]
opt-level = 3 # inspired by https://bevy-cheatbook.github.io/pitfalls/performance.html
