[package]
name = "rustaclysm"
version = "0.1.0"
description = "A 3D reimplementation of Cataclysm: Dark Days Ahead using Bevy"
license = "AGPL-3.0-or-later"
readme = "readme.md"
repository = "https://github.com/papow65/rustaclysm"
authors = [ "papow65 <papow65@protonmail.com>" ]
exclude = [ "/screenshots/" ]
edition = "2021"
rust-version = "1.76" # should be latest stable

[dependencies]
base64 = "0.21"
bevy = { version = "0.13", default-features = false, features = [ "bevy_asset", "bevy_core_pipeline", "bevy_pbr", "bevy_text", "bevy_ui", "ktx2", "multi-threaded", "png", "tonemapping_luts", "wayland", "x11" ] }
bresenham = "0.1"
either = "1"
float-ord = "0.3"
futures-lite = "2"
glob = "0.3"
pathfinding = "4"
fastrand = "2"
regex = "1"
serde = { version = "1", features = ["derive", "rc" ] }
serde_json = "1"
thread_local = "1"
time = "0.3"

[features]
log_archetypes = [] # print archetypes in use

[profile.dev]
opt-level = 3 # inspired by https://bevy-cheatbook.github.io/pitfalls/performance.html

[profile.release]
lto = "thin"

[lints.rust]
# Forbidden
absolute_paths_not_starting_with_crate = "forbid"
ambiguous_associated_items = "forbid"
anonymous_parameters = "forbid"
array_into_iter = "forbid"
bare_trait_objects = "forbid"
cenum_impl_drop_cast = "forbid"
coherence_leak_check = "forbid"
conflicting_repr_hints = "forbid"
const_evaluatable_unchecked = "forbid"
deref_into_dyn_supertrait = "forbid"
ellipsis_inclusive_range_patterns = "forbid"
explicit_outlives_requirements = "forbid"
forbidden_lint_groups = "forbid"
ill_formed_attribute_input = "forbid"
illegal_floating_point_literal_pattern = "forbid"
indirect_structural_match = "forbid"
invalid_doc_attributes = "forbid"
invalid_type_param_default = "forbid"
keyword_idents = "forbid"
late_bound_lifetime_arguments = "forbid"
legacy_derive_helpers = "forbid"
macro_expanded_macro_exports_accessed_by_absolute_paths = "forbid"
missing_fragment_specifier = "forbid"
non_fmt_panics = "forbid"
non_snake_case = "forbid"
nontrivial_structural_match = "forbid"
order_dependent_trait_objects = "forbid"
patterns_in_fns_without_body = "forbid"
pointer_structural_match = "forbid"
private_interfaces = "forbid"
private_bounds = "forbid"
proc_macro_back_compat = "forbid"
proc_macro_derive_resolution_fallback = "forbid"
pub_use_of_private_extern_crate = "forbid"
rust_2021_incompatible_closure_captures = "forbid"
rust_2021_incompatible_or_patterns = "forbid"
rust_2021_prefixes_incompatible_syntax = "forbid"
rust_2021_prelude_collisions = "forbid"
semicolon_in_expressions_from_macros = "forbid"
soft_unstable = "forbid"
tyvar_behind_raw_pointer = "forbid"
uninhabited_static = "forbid"
unsafe_code = "forbid"
unstable_name_collisions = "forbid"
unsupported_calling_conventions = "forbid"
where_clauses_object_safety = "forbid"
# Denied
non_camel_case_types = "deny"
non_upper_case_globals = "deny"
unreachable_code = "deny"
unreachable_pub = "deny"
unused_attributes = "deny"
unused_extern_crates = "deny"
unused_macros = "deny"
# Warned
dead_code = "warn"

[lints.clippy]
# Denied categories
complexity = "deny"
correctness = "deny"
pedantic = "deny"
perf = "deny"
style = "deny"
suspicious = "deny"
# Denied lints from allowed categories
assertions_on_result_states = "deny"
disallowed_script_idents = "deny"
infinite_loop = "deny"
join_absolute_paths = "deny"
modulo_arithmetic = "deny"
str_to_string = "deny"
missing_assert_message = "deny"
missing_const_for_fn = "deny"
mixed_read_write_in_expression = "deny"
option_map_or_err_ok = "deny"
repeat_vec_with_capacity = "deny"
test_attr_in_doctest = "deny"
unwrap_used = "deny"
use_self = "deny"
uninhabited_references = "deny"
unneeded_field_pattern = "deny"
unseparated_literal_suffix = "deny"
verbose_file_reads = "deny"
# Exceptions for allowed lints from denied categories
cast_possible_truncation = { level = "allow", priority = 1 }
cast_precision_loss = { level = "allow", priority = 1 }
cast_possible_wrap = { level = "allow", priority = 1 }
cast_sign_loss = { level = "allow", priority = 1 }
match_wildcard_for_single_variants = { level = "allow", priority = 1 }
module_name_repetitions = { level = "allow", priority = 1 }
redundant_else = { level = "allow", priority = 1 }
similar_names = { level = "allow", priority = 1 }
struct_field_names = { level = "allow", priority = 1 } # doens't work well with CDDA data
too_many_arguments = { level = "allow", priority = 1 } # doesn't work well with bevy
trivially_copy_pass_by_ref = { level = "allow", priority = 1 }
type_complexity = { level = "allow", priority = 1 } # doesn't work well with bevy
