[package]
name = "rustaclysm"
version = "0.1.0"
description = "A 3D reimplementation of Cataclysm: Dark Days Ahead using Bevy"
license = "AGPL-3.0-or-later"
readme = "readme.md"
repository = "https://github.com/papow65/rustaclysm"
authors = [ "papow65 <papow65@protonmail.com>" ]
exclude = [ "/screenshots/" ]
edition = "2021"

[dependencies]
base64 = "0.21"
bevy = { version = "0.12", default-features = false, features = [ "bevy_asset", "bevy_core_pipeline", "bevy_pbr", "bevy_text", "bevy_ui", "ktx2", "multi-threaded", "png", "tonemapping_luts", "wayland", "x11" ] }
bresenham = "0.1"
either = "1"
float-ord = "0.3"
futures-lite = "2"
glob = "0.3"
pathfinding = "4"
fastrand = "2"
regex = "1"
serde = { version = "1", features = ["derive", "rc" ] }
serde_json = "1"
time = "0.3"

[profile.dev]
opt-level = 3 # inspired by https://bevy-cheatbook.github.io/pitfalls/performance.html

[profile.release]
lto = "thin"
