[package]
name = "rustaclysm"
version = "0.1.0"
description = "A 3D reimplementation of Cataclysm: Dark Days Ahead using Bevy"
license = "AGPL-3.0-or-later"
readme = "readme.md"
repository = "https://github.com/papow65/rustaclysm"
homepage = "https://github.com/papow65/rustaclysm"
authors = [ "papow65 <papow65@protonmail.com>" ]
exclude = [ "/screenshots/" ]
edition = "2021"

[dependencies]
bevy = { version = "0.10", default-features = false, features = [ "bevy_asset", "bevy_core_pipeline", "bevy_pbr", "bevy_sprite", "bevy_text", "bevy_ui", "png", "wayland", "x11" ] }
pathfinding = "4"
bresenham = "0.1"
rand = "0.8"
serde = { version = "1", features = [ "derive" ] }
serde_json = "1"
glob = "0.3"
float-ord = "0.3"
time = "0.3"
base64 = "0.21.0"
#bevy_mod_debugdump = "0.7.0"

[profile.dev]
opt-level = 3 # inspired by https://bevy-cheatbook.github.io/pitfalls/performance.html

[profile.release]
lto = "thin"
