[package]
name = "gameplay_resource"
description = "Plugin for gameplay-scoped resources"
license = "AGPL-3.0-or-later"
edition = "2024"

[dependencies]
application_state = { workspace = true }
bevy = { workspace = true }

[lints]
workspace = true
