use bevy_platform::collections::HashMap;
use serde::Deserialize;
use serde_json::Value as JsonValue;
use std::sync::Arc;

#[derive(Debug, Deserialize)]
pub struct CddaPlayer {
    pub str_max: i16,
    pub str_bonus: i16,
    pub str_cur: i16,
    pub dex_max: i16,
    pub dex_bonus: i16,
    pub dex_cur: i16,
    pub int_max: i16,
    pub int_bonus: i16,
    pub int_cur: i16,
    pub per_max: i16,
    pub per_bonus: i16,
    pub per_cur: i16,
    //pub active_mission: JsonValue,
    //pub active_missions: JsonValue,
    //pub activity: JsonValue,
    //pub activity_history: JsonValue,
    //pub activity_vehicle_part_index: JsonValue,
    //pub addictions: JsonValue,
    //pub archery_aim_counter: JsonValue,
    //pub armor_bash_bonus: JsonValue,
    //pub armor_bullet_bonus: JsonValue,
    //pub armor_cut_bonus: JsonValue,
    //pub assigned_invlet: JsonValue,
    //pub automoveroute: JsonValue,
    //pub avg_nat_bpm: JsonValue,
    //pub backlog: JsonValue,
    //pub base_age: JsonValue,
    //pub base_height: JsonValue,
    //pub bash_bonus: JsonValue,
    //pub bash_mult: JsonValue,
    //pub block_bonus: JsonValue,
    //pub blocks_left: JsonValue,
    //pub blood_rh_factor: JsonValue,
    //pub blood_type: JsonValue,
    pub body: JsonValue,
    //pub calorie_diary: JsonValue,
    //pub camps: JsonValue,
    //pub cardio_acc: JsonValue,
    //pub cash: JsonValue,
    //pub completed_missions: JsonValue,
    //pub consumption_history: JsonValue,
    //pub continuous_sleep: JsonValue,
    //pub controlling_vehicle: JsonValue,
    //pub custom_profession: JsonValue,
    //pub cut_bonus: JsonValue,
    //pub cut_mult: JsonValue,
    //pub daily_sleep: JsonValue,
    //pub daily_vitamins: JsonValue,
    //pub damage_over_time_map: JsonValue,
    //pub death_eocs: JsonValue,
    //pub destination_activity: JsonValue,
    //pub destination_point: JsonValue,
    //pub dodge_bonus: JsonValue,
    //pub dodges_left: JsonValue,
    //pub effects: JsonValue,
    //pub faction_warnings: JsonValue,
    //pub failed_missions: JsonValue,
    //pub fatigue: JsonValue,
    pub focus_pool: JsonValue,
    //pub followers: JsonValue,
    //pub grab_point: JsonValue,
    //pub grab_type: JsonValue,
    //pub guts: JsonValue,
    //pub health_tally: JsonValue,
    //pub healthy: JsonValue,
    //pub healthy_mod: JsonValue,
    //pub hit_bonus: JsonValue,
    //pub hunger: JsonValue,
    pub id: JsonValue,
    //pub in_vehicle: JsonValue,
    //pub inactive_eocs: JsonValue,
    //pub inv: JsonValue,
    //pub invcache: JsonValue,
    pub items_identified: JsonValue,
    //pub kill_xp: JsonValue,
    //pub known_monsters: JsonValue,
    //pub known_traps: JsonValue,
    //pub last_sleep_check: JsonValue,
    //pub last_target_pos: JsonValue,
    //pub last_updated: JsonValue,
    //pub learned_recipes: JsonValue,
    //pub location: JsonValue,
    //pub magic: JsonValue,
    //pub male: JsonValue,
    //pub martial_arts_data: JsonValue,
    //pub max_power_level_modifier: Option<JsonValue>,
    //pub melee_quiet: JsonValue,
    //pub moncams: Option<JsonValue>,
    //pub morale: JsonValue,
    //pub move_mode: JsonValue,
    //pub moves: JsonValue,
    //pub mutations: JsonValue,
    //pub my_bionics: JsonValue,
    pub name: Arc<str>,
    //pub num_blocks_bonus: JsonValue,
    //pub num_dodges_bonus: JsonValue,
    pub omt_path: JsonValue,
    pub oxygen: JsonValue,
    pub pain: JsonValue,
    pub pkill: JsonValue,
    pub play_name: JsonValue,
    //pub power_level: JsonValue,
    //pub power_prev_turn: JsonValue,
    //pub preferred_aiming_mode: JsonValue,
    //pub profession: JsonValue,
    //pub proficiencies: JsonValue,
    //pub queued_effect_on_conditions: JsonValue,
    //pub radiation: JsonValue,
    //pub recoil: JsonValue,
    //pub scenario: JsonValue,
    //pub scent: JsonValue,
    //pub show_map_memory: JsonValue,
    pub skills: HashMap<Arc<str>, Skill>,
    pub sleep_deprivation: JsonValue,
    //pub slow_rad: JsonValue,
    //pub snippets_read: JsonValue,
    //pub speed: JsonValue,
    //pub speed_bonus: JsonValue,
    //pub spent_upgrade_points: JsonValue,
    pub stamina: JsonValue,
    //pub stashed_outbounds_activity: JsonValue,
    //pub stashed_outbounds_backlog: JsonValue,
    //pub stim: JsonValue,
    //pub stomach: JsonValue,
    //pub stored_calories: JsonValue,
    //pub thirst: JsonValue,
    //pub throw_resist: JsonValue,
    pub traits: JsonValue,
    //pub translocators: JsonValue,
    //pub type_of_scent: JsonValue,
    //pub underwater: JsonValue,
    //pub values: JsonValue,
    //pub vitamin_levels: JsonValue,
    //pub worn: JsonValue,

    // To prevent a linking eror when there Too many fields to deserialize
    #[serde(flatten)]
    pub extra: HashMap<Arc<str>, JsonValue>,
}

#[derive(Debug, Deserialize)]
pub struct Skill {
    pub level: u8,

    #[expect(unused)]
    #[serde(flatten)]
    extra: HashMap<Arc<str>, JsonValue>,
}
