[package]
name = "pre_gameplay"
description = "Preparation the gameplay"
license = "AGPL-3.0-or-later"
edition = "2024"

[dependencies]
application_state = { workspace = true }
bevy = { workspace = true }
gameplay = { workspace = true }

[lints]
workspace = true
