[package]
name = "util"
description = "A library of small utils"
license = "AGPL-3.0-or-later"
edition = "2024"

[dependencies]
bevy = { workspace = true }
futures-lite = { version = "2", default-features = false }
regex = { workspace = true }

[lints]
workspace = true
