[package]
name = "manual"
description = "A library of to display a manual"
license = "AGPL-3.0-or-later"
edition = "2024"

[dependencies]
bevy = { workspace = true }
hud = { workspace = true }
keyboard = { workspace = true }
util = { workspace = true }

[lints]
workspace = true
