[package]
name = "units"
description = "A library for expressing physical units relevant to this game"
license = "AGPL-3.0-or-later"
edition = "2021"

[dependencies]
pathfinding = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
time = "0.3"

[lints]
workspace = true
