[package]
name = "gameplay"
description = "Everything in-game"
license = "AGPL-3.0-or-later"
edition = "2024"

[dependencies]
application_state = { path = "../application_state" }
bevy = { workspace = true }
bresenham = "0.1"
cdda_json_files = { path = "../cdda_json_files" }
either = { workspace = true }
fastrand = { workspace = true }
float-ord = "0.3"
glob = { workspace = true }
hud = { path = "../hud" }
keyboard = { path = "../keyboard" }
manual = { path = "../manual" }
pathfinding = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
strum = { workspace = true }
thread_local = "1"
units = { path = "../units" }
util = { workspace = true }

[lints]
workspace = true
