[package]
name = "loading"
description = "A loading indicator"
license = "AGPL-3.0-or-later"
edition = "2024"

[dependencies]
application_state = { workspace = true }
bevy = { workspace = true }
gameplay = { workspace = true }
hud = { workspace = true }
util = { workspace = true }

[lints]
workspace = true
