[package]
name = "loading"
description = "A loading indicator"
license = "AGPL-3.0-or-later"
edition = "2024"

[dependencies]
application_state = { path = "../application_state" }
bevy = { workspace = true }
gameplay = { path = "../gameplay" }
hud = { path = "../hud" }
util = { path = "../util" }

[lints]
workspace = true
