[package]
name = "main_menu"
description = "The main menu"
license = "AGPL-3.0-or-later"
edition = "2024"

[dependencies]
application_state = { workspace = true }
base64 = "0.22"
bevy = { workspace = true }
gameplay_cdda = { workspace = true }
gameplay_local = { workspace = true }
glob = { workspace = true }
hud = { workspace = true }
manual = { workspace = true }
util = { workspace = true }

[lints]
workspace = true
