#![forbid(absolute_paths_not_starting_with_crate)]
#![forbid(ambiguous_associated_items)]
#![forbid(anonymous_parameters)]
#![forbid(array_into_iter)]
#![forbid(bare_trait_objects)]
#![forbid(cenum_impl_drop_cast)]
#![forbid(coherence_leak_check)]
#![forbid(conflicting_repr_hints)]
#![forbid(const_err)]
#![forbid(const_evaluatable_unchecked)]
#![forbid(deref_into_dyn_supertrait)]
#![forbid(ellipsis_inclusive_range_patterns)]
#![forbid(explicit_outlives_requirements)]
#![forbid(forbidden_lint_groups)]
#![forbid(ill_formed_attribute_input)]
#![forbid(illegal_floating_point_literal_pattern)]
#![forbid(indirect_structural_match)]
#![forbid(invalid_doc_attributes)]
#![forbid(invalid_type_param_default)]
#![forbid(keyword_idents)]
#![forbid(late_bound_lifetime_arguments)]
#![forbid(legacy_derive_helpers)]
#![forbid(macro_expanded_macro_exports_accessed_by_absolute_paths)]
#![forbid(missing_fragment_specifier)]
#![forbid(mutable_borrow_reservation_conflict)]
#![forbid(non_fmt_panics)]
#![forbid(non_snake_case)]
#![forbid(nontrivial_structural_match)]
#![forbid(order_dependent_trait_objects)]
#![forbid(path_statements)]
#![forbid(patterns_in_fns_without_body)]
#![forbid(pointer_structural_match)]
#![forbid(private_in_public)]
#![forbid(proc_macro_back_compat)]
#![forbid(proc_macro_derive_resolution_fallback)]
#![forbid(pub_use_of_private_extern_crate)]
#![forbid(redundant_semicolons)]
#![forbid(rust_2021_incompatible_closure_captures)]
#![forbid(rust_2021_incompatible_or_patterns)]
#![forbid(rust_2021_prefixes_incompatible_syntax)]
#![forbid(rust_2021_prelude_collisions)]
#![forbid(semicolon_in_expressions_from_macros)]
#![forbid(soft_unstable)]
#![forbid(tyvar_behind_raw_pointer)]
#![forbid(unaligned_references)]
#![forbid(uninhabited_static)]
#![forbid(unreachable_patterns)]
#![forbid(unstable_name_collisions)]
#![forbid(unsupported_calling_conventions)]
#![forbid(unsupported_naked_functions)]
#![forbid(unused_allocation)]
#![forbid(unused_assignments)]
#![forbid(unused_braces)]
#![forbid(unused_doc_comments)]
#![forbid(unused_features)]
#![forbid(unused_imports)]
#![forbid(unused_labels)]
#![forbid(unused_must_use)]
#![forbid(unused_mut)]
#![forbid(unused_parens)]
#![forbid(unused_unsafe)]
#![forbid(unused_variables)]
#![forbid(where_clauses_object_safety)]
#![warn(dead_code)]
#![deny(non_camel_case_types)]
#![deny(non_upper_case_globals)]
#![deny(unreachable_code)]
#![deny(unused_attributes)]
#![deny(unused_extern_crates)]
#![deny(unused_macros)]
#![deny(clippy::cloned_instead_of_copied)]
#![deny(clippy::default_trait_access)]
#![deny(clippy::explicit_iter_loop)]
#![deny(clippy::flat_map_option)]
#![deny(clippy::implicit_clone)]
#![deny(clippy::map_flatten)]
#![deny(clippy::missing_const_for_fn)]
#![deny(clippy::needless_pass_by_value)]
#![deny(clippy::redundant_closure_for_method_calls)]
#![deny(clippy::ref_binding_to_reference)]
#![deny(clippy::semicolon_if_nothing_returned)]
#![deny(clippy::unreadable_literal)]
#![deny(clippy::unseparated_literal_suffix)]
#![deny(clippy::use_self)]
#![allow(clippy::too_many_arguments)]
#![allow(clippy::type_complexity)]

mod components;
mod plugin;
mod resources;
mod systems;
mod units;

use bevy::diagnostic::FrameTimeDiagnosticsPlugin;
use bevy::prelude::{App, DefaultPlugins};

use plugin::RustaclysmPlugin;

fn main() {
    App::build()
        .add_plugin(RustaclysmPlugin) // first, to prevent vulkan errors
        .add_plugins(DefaultPlugins)
        .add_plugin(FrameTimeDiagnosticsPlugin::default())
        .run();
}
