on: [push]

name: CI

jobs:
  build_and_test:
    name: Test and build on ubuntu
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install libwayland-dev -y
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: test
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
