on:
  push:
    branches:
      - 'main'

name: CI

jobs:
  test_build_and_release:
    name: Test, build, and release
    runs-on: ubuntu-latest
    steps:
      - name: 'Install required libraries'
        run: sudo apt install -y libwayland-dev libxkbcommon-dev
      - name: 'git checkout'
        uses: actions/checkout@v2
      - name: 'Install rust toolchain'
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: 'Test'
        uses: actions-rs/cargo@v1
        with:
          command: test
      - name: 'Build'
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: 'Release'
        uses: ncipollo/release-action@v1
        with:
          artifacts: "target/release/rustaclysm"
